server:
  port: 1401
spring:
  application:
    name: feign-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
ribbon:
  ConnectTimeout: 500
  ReadTimeout: 500
hello-service:
  ribbon:
    ReadTimeout: 2000
    OkToRetryOnAllOperation: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1
hystrix:
  command:
    default:
#      execution:
#        timeout:
#          enabled: false #关闭熔断功能
      isolation:
        thread:
          timeoutInMilliseconds: 5000
#feign:
#  hystrix:
#    enabled: false   #关闭Feign对Hystrix的支持

